// AUTO-GENERATED by scripts/generate-db-types.mjs.
// DO NOT EDIT THIS FILE DIRECTLY — re-run `npm run db:types` after schema changes.
//
// Generated by introspecting a pglite (real Postgres 18) instance with the
// Phase 1 migrations applied. In an environment with the Supabase CLI
// available, this file can be regenerated with:
//   supabase gen types typescript --local > src/types/database.generated.ts
// The output shape is identical — pglite introspection is the verifiable
// alternative documented in README.md (Phase 1 limitation).

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | Json[] }
  | Json[];

export type JsonValue = Json;

export interface Database {
  public: {
    Tables: {

      audit_logs: {
        Row: {
        id: string;
        actor_id: string | null;
        action: string;
        entity_type: string;
        entity_id: string;
        reason: string | null;
        metadata: JsonValue | null;
        created_at: string;
        };
        Insert: {
        id?: string;
        actor_id?: string | null;
        action: string;
        entity_type: string;
        entity_id: string;
        reason?: string | null;
        metadata?: JsonValue | null;
        created_at?: string;
        };
        Update: {
        id?: string;
        actor_id?: string | null;
        action?: string;
        entity_type?: string;
        entity_id?: string;
        reason?: string | null;
        metadata?: JsonValue | null;
        created_at?: string;
        };
        Relationships: [
        { foreignKeyName: "none"; columns: ["actor_id"]; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ];
      };
      bookings: {
        Row: {
        id: string;
        room_id: string;
        property_id: string;
        landlord_id: string;
        student_id: string;
        status: Database["public"]["Enums"]["booking_status"];
        reserved_price: number;
        hold_expires_at: string;
        confirmed_at: string | null;
        cancelled_at: string | null;
        cancelled_by: string | null;
        cancellation_reason: string | null;
        completed_at: string | null;
        created_at: string;
        updated_at: string;
        };
        Insert: {
        id?: string;
        room_id: string;
        property_id: string;
        landlord_id: string;
        student_id: string;
        status?: Database["public"]["Enums"]["booking_status"];
        reserved_price: number;
        hold_expires_at: string;
        confirmed_at?: string | null;
        cancelled_at?: string | null;
        cancelled_by?: string | null;
        cancellation_reason?: string | null;
        completed_at?: string | null;
        created_at?: string;
        updated_at?: string;
        };
        Update: {
        id?: string;
        room_id?: string;
        property_id?: string;
        landlord_id?: string;
        student_id?: string;
        status?: Database["public"]["Enums"]["booking_status"];
        reserved_price?: number;
        hold_expires_at?: string;
        confirmed_at?: string | null;
        cancelled_at?: string | null;
        cancelled_by?: string | null;
        cancellation_reason?: string | null;
        completed_at?: string | null;
        created_at?: string;
        updated_at?: string;
        };
        Relationships: [
        { foreignKeyName: "none"; columns: ["cancelled_by"]; referencedRelation: "profiles"; referencedColumns: ["id"] },
        { foreignKeyName: "none"; columns: ["property_id"]; referencedRelation: "properties"; referencedColumns: ["id"] },
        { foreignKeyName: "none"; columns: ["room_id"]; referencedRelation: "rooms"; referencedColumns: ["id"] },
        { foreignKeyName: "none"; columns: ["student_id"]; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ];
      };
      landlord_verifications: {
        Row: {
        id: string;
        landlord_id: string;
        status: Database["public"]["Enums"]["verification_status"];
        submitted_id_reference: string;
        submitted_ownership_reference: string;
        submitted_at: string;
        reviewed_by: string | null;
        reviewed_at: string | null;
        decision: Database["public"]["Enums"]["decision_type"] | null;
        decision_reason: string | null;
        };
        Insert: {
        id?: string;
        landlord_id: string;
        status?: Database["public"]["Enums"]["verification_status"];
        submitted_id_reference: string;
        submitted_ownership_reference: string;
        submitted_at?: string;
        reviewed_by?: string | null;
        reviewed_at?: string | null;
        decision?: Database["public"]["Enums"]["decision_type"] | null;
        decision_reason?: string | null;
        };
        Update: {
        id?: string;
        landlord_id?: string;
        status?: Database["public"]["Enums"]["verification_status"];
        submitted_id_reference?: string;
        submitted_ownership_reference?: string;
        submitted_at?: string;
        reviewed_by?: string | null;
        reviewed_at?: string | null;
        decision?: Database["public"]["Enums"]["decision_type"] | null;
        decision_reason?: string | null;
        };
        Relationships: [
        { foreignKeyName: "none"; columns: ["landlord_id"]; referencedRelation: "landlords"; referencedColumns: ["profile_id"] },
        { foreignKeyName: "none"; columns: ["reviewed_by"]; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ];
      };
      landlords: {
        Row: {
        profile_id: string;
        current_verification_status: Database["public"]["Enums"]["verification_status"];
        verification_valid_until: string | null;
        is_suspended: boolean;
        suspension_reason: string | null;
        created_at: string;
        updated_at: string;
        };
        Insert: {
        profile_id: string;
        current_verification_status?: Database["public"]["Enums"]["verification_status"];
        verification_valid_until?: string | null;
        is_suspended?: boolean;
        suspension_reason?: string | null;
        created_at?: string;
        updated_at?: string;
        };
        Update: {
        profile_id?: string;
        current_verification_status?: Database["public"]["Enums"]["verification_status"];
        verification_valid_until?: string | null;
        is_suspended?: boolean;
        suspension_reason?: string | null;
        created_at?: string;
        updated_at?: string;
        };
        Relationships: [
        { foreignKeyName: "none"; columns: ["profile_id"]; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ];
      };
      payment_transactions: {
        Row: {
        id: string;
        booking_id: string;
        paystack_reference: string;
        amount: number;
        currency: string;
        status: Database["public"]["Enums"]["payment_status"];
        initiated_at: string;
        verified_at: string | null;
        failure_reason: string | null;
        provider_metadata: JsonValue | null;
        created_at: string;
        updated_at: string;
        };
        Insert: {
        id?: string;
        booking_id: string;
        paystack_reference: string;
        amount: number;
        currency?: string;
        status?: Database["public"]["Enums"]["payment_status"];
        initiated_at?: string;
        verified_at?: string | null;
        failure_reason?: string | null;
        provider_metadata?: JsonValue | null;
        created_at?: string;
        updated_at?: string;
        };
        Update: {
        id?: string;
        booking_id?: string;
        paystack_reference?: string;
        amount?: number;
        currency?: string;
        status?: Database["public"]["Enums"]["payment_status"];
        initiated_at?: string;
        verified_at?: string | null;
        failure_reason?: string | null;
        provider_metadata?: JsonValue | null;
        created_at?: string;
        updated_at?: string;
        };
        Relationships: [
        { foreignKeyName: "none"; columns: ["booking_id"]; referencedRelation: "bookings"; referencedColumns: ["id"] },
        ];
      };
      payment_webhook_events: {
        Row: {
        id: string;
        provider_event_id: string;
        paystack_reference: string;
        event_type: string;
        received_at: string;
        processed_at: string | null;
        processing_outcome: Database["public"]["Enums"]["webhook_outcome"] | null;
        raw_payload: JsonValue;
        };
        Insert: {
        id?: string;
        provider_event_id: string;
        paystack_reference: string;
        event_type: string;
        received_at?: string;
        processed_at?: string | null;
        processing_outcome?: Database["public"]["Enums"]["webhook_outcome"] | null;
        raw_payload: JsonValue;
        };
        Update: {
        id?: string;
        provider_event_id?: string;
        paystack_reference?: string;
        event_type?: string;
        received_at?: string;
        processed_at?: string | null;
        processing_outcome?: Database["public"]["Enums"]["webhook_outcome"] | null;
        raw_payload?: JsonValue;
        };
        Relationships: [
        
        ];
      };
      profiles: {
        Row: {
        id: string;
        role: Database["public"]["Enums"]["user_role"];
        full_name: string;
        phone: string;
        university_id: string | null;
        account_status: Database["public"]["Enums"]["account_status"];
        suspension_reason: string | null;
        created_at: string;
        updated_at: string;
        };
        Insert: {
        id: string;
        role: Database["public"]["Enums"]["user_role"];
        full_name: string;
        phone: string;
        university_id?: string | null;
        account_status?: Database["public"]["Enums"]["account_status"];
        suspension_reason?: string | null;
        created_at?: string;
        updated_at?: string;
        };
        Update: {
        id?: string;
        role?: Database["public"]["Enums"]["user_role"];
        full_name?: string;
        phone?: string;
        university_id?: string | null;
        account_status?: Database["public"]["Enums"]["account_status"];
        suspension_reason?: string | null;
        created_at?: string;
        updated_at?: string;
        };
        Relationships: [
        { foreignKeyName: "none"; columns: ["id"]; referencedRelation: "auth.users"; referencedColumns: ["id"] },
        { foreignKeyName: "none"; columns: ["university_id"]; referencedRelation: "universities"; referencedColumns: ["id"] },
        ];
      };
      properties: {
        Row: {
        id: string;
        landlord_id: string;
        university_id: string;
        area: string;
        address: string;
        description: string;
        status: Database["public"]["Enums"]["property_status"];
        created_at: string;
        updated_at: string;
        is_suspended: boolean;
        suspension_reason: string | null;
        };
        Insert: {
        id?: string;
        landlord_id: string;
        university_id: string;
        area: string;
        address: string;
        description: string;
        status?: Database["public"]["Enums"]["property_status"];
        created_at?: string;
        updated_at?: string;
        is_suspended?: boolean;
        suspension_reason?: string | null;
        };
        Update: {
        id?: string;
        landlord_id?: string;
        university_id?: string;
        area?: string;
        address?: string;
        description?: string;
        status?: Database["public"]["Enums"]["property_status"];
        created_at?: string;
        updated_at?: string;
        is_suspended?: boolean;
        suspension_reason?: string | null;
        };
        Relationships: [
        { foreignKeyName: "none"; columns: ["landlord_id"]; referencedRelation: "landlords"; referencedColumns: ["profile_id"] },
        { foreignKeyName: "none"; columns: ["university_id"]; referencedRelation: "universities"; referencedColumns: ["id"] },
        ];
      };
      property_images: {
        Row: {
        id: string;
        property_id: string;
        storage_path: string;
        position: number;
        is_primary: boolean;
        uploaded_by: string;
        created_at: string;
        };
        Insert: {
        id?: string;
        property_id: string;
        storage_path: string;
        position?: number;
        is_primary?: boolean;
        uploaded_by: string;
        created_at?: string;
        };
        Update: {
        id?: string;
        property_id?: string;
        storage_path?: string;
        position?: number;
        is_primary?: boolean;
        uploaded_by?: string;
        created_at?: string;
        };
        Relationships: [
        { foreignKeyName: "none"; columns: ["property_id"]; referencedRelation: "properties"; referencedColumns: ["id"] },
        { foreignKeyName: "none"; columns: ["uploaded_by"]; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ];
      };
      property_reviews: {
        Row: {
        id: string;
        property_id: string;
        submitted_at: string;
        reviewed_by: string | null;
        reviewed_at: string | null;
        decision: Database["public"]["Enums"]["decision_type"] | null;
        decision_reason: string | null;
        };
        Insert: {
        id?: string;
        property_id: string;
        submitted_at?: string;
        reviewed_by?: string | null;
        reviewed_at?: string | null;
        decision?: Database["public"]["Enums"]["decision_type"] | null;
        decision_reason?: string | null;
        };
        Update: {
        id?: string;
        property_id?: string;
        submitted_at?: string;
        reviewed_by?: string | null;
        reviewed_at?: string | null;
        decision?: Database["public"]["Enums"]["decision_type"] | null;
        decision_reason?: string | null;
        };
        Relationships: [
        { foreignKeyName: "none"; columns: ["property_id"]; referencedRelation: "properties"; referencedColumns: ["id"] },
        { foreignKeyName: "none"; columns: ["reviewed_by"]; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ];
      };
      reports: {
        Row: {
        id: string;
        reporter_id: string;
        reported_entity_type: Database["public"]["Enums"]["report_target"];
        reported_entity_id: string;
        reason_category: string;
        description: string | null;
        status: Database["public"]["Enums"]["report_status"];
        resolved_by: string | null;
        resolution_notes: string | null;
        resolved_at: string | null;
        created_at: string;
        };
        Insert: {
        id?: string;
        reporter_id: string;
        reported_entity_type: Database["public"]["Enums"]["report_target"];
        reported_entity_id: string;
        reason_category: string;
        description?: string | null;
        status?: Database["public"]["Enums"]["report_status"];
        resolved_by?: string | null;
        resolution_notes?: string | null;
        resolved_at?: string | null;
        created_at?: string;
        };
        Update: {
        id?: string;
        reporter_id?: string;
        reported_entity_type?: Database["public"]["Enums"]["report_target"];
        reported_entity_id?: string;
        reason_category?: string;
        description?: string | null;
        status?: Database["public"]["Enums"]["report_status"];
        resolved_by?: string | null;
        resolution_notes?: string | null;
        resolved_at?: string | null;
        created_at?: string;
        };
        Relationships: [
        { foreignKeyName: "none"; columns: ["reporter_id"]; referencedRelation: "profiles"; referencedColumns: ["id"] },
        { foreignKeyName: "none"; columns: ["resolved_by"]; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ];
      };
      reviews: {
        Row: {
        id: string;
        booking_id: string;
        student_id: string;
        room_id: string;
        rating: number;
        content: string;
        is_hidden: boolean;
        hidden_reason: string | null;
        created_at: string;
        updated_at: string;
        };
        Insert: {
        id?: string;
        booking_id: string;
        student_id: string;
        room_id: string;
        rating: number;
        content: string;
        is_hidden?: boolean;
        hidden_reason?: string | null;
        created_at?: string;
        updated_at?: string;
        };
        Update: {
        id?: string;
        booking_id?: string;
        student_id?: string;
        room_id?: string;
        rating?: number;
        content?: string;
        is_hidden?: boolean;
        hidden_reason?: string | null;
        created_at?: string;
        updated_at?: string;
        };
        Relationships: [
        { foreignKeyName: "none"; columns: ["booking_id"]; referencedRelation: "bookings"; referencedColumns: ["id"] },
        { foreignKeyName: "none"; columns: ["room_id"]; referencedRelation: "rooms"; referencedColumns: ["id"] },
        { foreignKeyName: "none"; columns: ["student_id"]; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ];
      };
      room_images: {
        Row: {
        id: string;
        room_id: string;
        storage_path: string;
        position: number;
        is_primary: boolean;
        uploaded_by: string;
        created_at: string;
        };
        Insert: {
        id?: string;
        room_id: string;
        storage_path: string;
        position?: number;
        is_primary?: boolean;
        uploaded_by: string;
        created_at?: string;
        };
        Update: {
        id?: string;
        room_id?: string;
        storage_path?: string;
        position?: number;
        is_primary?: boolean;
        uploaded_by?: string;
        created_at?: string;
        };
        Relationships: [
        { foreignKeyName: "none"; columns: ["room_id"]; referencedRelation: "rooms"; referencedColumns: ["id"] },
        { foreignKeyName: "none"; columns: ["uploaded_by"]; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ];
      };
      rooms: {
        Row: {
        id: string;
        property_id: string;
        room_type: string;
        price: number;
        occupancy: number;
        amenities: Array<string>;
        is_listed: boolean;
        created_at: string;
        updated_at: string;
        };
        Insert: {
        id?: string;
        property_id: string;
        room_type: string;
        price: number;
        occupancy: number;
        amenities?: Array<string>;
        is_listed?: boolean;
        created_at?: string;
        updated_at?: string;
        };
        Update: {
        id?: string;
        property_id?: string;
        room_type?: string;
        price?: number;
        occupancy?: number;
        amenities?: Array<string>;
        is_listed?: boolean;
        created_at?: string;
        updated_at?: string;
        };
        Relationships: [
        { foreignKeyName: "none"; columns: ["property_id"]; referencedRelation: "properties"; referencedColumns: ["id"] },
        ];
      };
      universities: {
        Row: {
        id: string;
        name: string;
        city: string;
        state: string;
        is_active: boolean;
        created_at: string;
        };
        Insert: {
        id?: string;
        name: string;
        city: string;
        state: string;
        is_active?: boolean;
        created_at?: string;
        };
        Update: {
        id?: string;
        name?: string;
        city?: string;
        state?: string;
        is_active?: boolean;
        created_at?: string;
        };
        Relationships: [
        
        ];
      };


    };
    Views: { [key: string]: never };
    Functions: { [key: string]: never };
    Enums: {
      account_status: "active" | "suspended";
      booking_status: "reservation_pending" | "payment_pending" | "confirmed" | "payment_failed" | "expired" | "cancelled" | "completed";
      decision_type: "approved" | "rejected";
      payment_status: "initiated" | "pending" | "success" | "failed" | "expired";
      property_status: "draft" | "submitted" | "under_review" | "approved" | "rejected" | "archived";
      report_status: "open" | "under_review" | "resolved";
      report_target: "property" | "room" | "user";
      user_role: "student" | "landlord" | "admin";
      verification_status: "unsubmitted" | "submitted" | "under_review" | "approved" | "rejected";
      webhook_outcome: "confirmed" | "duplicate_ignored" | "verification_failed" | "reconciliation_needed" | "malformed_payload";
    };
    CompositeTypes: { [key: string]: never };
  };
}
